name: first-pipeline
on:
  push:
    branches: ["main"]
  workflow_dispatch:
jobs:
  first-job:
    name: "My first Job"
    runs-on: ubuntu-latest
    steps:
      - name: "My first action"
        run: echo "Hello World"
      - name: "Second action"
        run: |
          echo "You've created your first workflow!"
          echo "Congratulations"
