name: first-pipeline
on:
  push:
    branches: ["main"]
  workflow_dispatch:
jobs:
  first-job:
    name: "My first Job"
    runs-on: ubuntu-latest
    steps:
      - name: "My first action"
        run: echo "Hello World"
      - name: "Second action"
        run: |
          echo "You've created your first workflow!"
          echo "Congratulations"
      - name: "Python Script"
        run: |
          hello_world_message = "Hello World!!"
          print(hello_world_message)
        shell: python
  second-job:
    name: "Node Enviroment Instalation"
    runs-on: ubuntu-latest
    needs: [first-job]
    steps:
      - name: "Node current version verification"
        run: node -v
      - name: "Node Latest LTS version definition"
        uses: actions/setup-node@v6
        with:
          node-version: '24.11.1'
      - name: "Node version verification after update"
        run: node -v
