name: install
on:
  workflow_dispatch:
jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - name: "Install FFMPEG"
        run: |
          sudo apt update --yes
          sudo apt install ffmpeg --yes
      - name: "Executar FFMPEG"
        run: |
          ffmpeg --help
